postgres:
  host: localhost
  post: 5432
  dbname: test-faucet
  user: postgres
  password: admino0o0oo0
  sslmode: disable
server: 0.0.0.0:3434 #server host:port
total: 70 #daily upper coin limit
amount: 11 #coin amount
coin: fermion #coin denom
iris: 0D7ACAD5C3F3EE3DBFB972F52D652509437E0044 #gaia account address
name: iris #gaia account name
password:  1234567890 #gaia account password
client: http://116.62.62.39:8999 #gaia client
