postgres:
  host: localhost
  post: 5432
  dbname: test-faucet
  user: postgres
  password: admino0o0oo0
  sslmode: disable
server: 0.0.0.0:3434
total: 100
amount: 10
denom: fermion
iris: 0D7ACAD5C3F3EE3DBFB972F52D652509437E0044
name: iris
password:
client: http://116.62.62.39:8999
